### ISSUE TITLE
Ошибка с session_write_close()

### ISSUE THREAD

**Issue by Globulopolis** [Romandry/phpsu#3]
Возникает если неверно указан логин или пароль к БД в настройках.

> Fatal error: Uncaught exception 'SystemErrorException' in D:\WWW\htdocs\su\application\core\DBC.php:56 Stack trace: #0 D:\WWW\htdocs\su\application\core\DBI.php(48): DBC->__construct(Object(stdClass)) #1 D:\WWW\htdocs\su\application\core\StorageDatabaseHandler.php(66): DBI::getConnection('master') #2 [internal function]: StorageDatabaseHandler->write('j2lm63fn9vshi98...', '') #3 [internal function]: session_write_close() #4 {main} thrown in D:\WWW\htdocs\su\application\core\DBC.php on line 56

PS! Проявляется на Windows7 64, MySQL 5.5.32, PHP 5.5.15 (VC11 X86 32bit thread safe) + PEAR

**Comment by DeepVarvar** [comment]
Давай, подтверждай уже что пофиксилось ))

**Comment by Globulopolis** [comment]
Fixed via 0994c9ace67c197ea64067d2a882c58c66f40f14
